# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 111a0b5b5c37275d302ff96dc5d2ee9ea633a9ca707019555de682d53ca010b3adb698cc83c96706d2df83c3eef6f2e9df7c3d48b6a8ecf90d4301e9cbe13c21

test:
  secret_key_base: 68ea921068e64c8816a47f2978ddbcba0274d9bae684bb4599726db4bd8b46106fa31d8d0554dad39c3506cf14a50a7a104e49539090b098a7f5a52a1aa56b27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
